/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as CourseSlugRouteImport } from './routes/$courseSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseSlugIndexRouteImport } from './routes/$courseSlug/index'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiDemoEventsRouteImport } from './routes/api/demo-events'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'
import { Route as CourseSlugDashboardRouteImport } from './routes/$courseSlug/dashboard'
import { Route as CourseSlugAdminRouteImport } from './routes/$courseSlug/admin'
import { Route as LessonLessonIdEditRouteImport } from './routes/lesson_.$lessonId.edit'
import { Route as CourseSlugLessonLessonIdRouteImport } from './routes/$courseSlug/lesson.$lessonId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugIndexRoute = CourseSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseSlugRoute,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoEventsRoute = ApiDemoEventsRouteImport.update({
  id: '/api/demo-events',
  path: '/api/demo-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugDashboardRoute = CourseSlugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CourseSlugRoute,
} as any)
const CourseSlugAdminRoute = CourseSlugAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CourseSlugRoute,
} as any)
const LessonLessonIdEditRoute = LessonLessonIdEditRouteImport.update({
  id: '/lesson_/$lessonId/edit',
  path: '/lesson/$lessonId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugLessonLessonIdRoute =
  CourseSlugLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => CourseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$courseSlug': typeof CourseSlugRouteWithChildren
  '/messages': typeof MessagesRoute
  '/test': typeof TestRoute
  '/$courseSlug/admin': typeof CourseSlugAdminRoute
  '/$courseSlug/dashboard': typeof CourseSlugDashboardRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/api/$': typeof ApiSplatRoute
  '/api/demo-events': typeof ApiDemoEventsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/$courseSlug/': typeof CourseSlugIndexRoute
  '/$courseSlug/lesson/$lessonId': typeof CourseSlugLessonLessonIdRoute
  '/lesson/$lessonId/edit': typeof LessonLessonIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/test': typeof TestRoute
  '/$courseSlug/admin': typeof CourseSlugAdminRoute
  '/$courseSlug/dashboard': typeof CourseSlugDashboardRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/api/$': typeof ApiSplatRoute
  '/api/demo-events': typeof ApiDemoEventsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/$courseSlug': typeof CourseSlugIndexRoute
  '/$courseSlug/lesson/$lessonId': typeof CourseSlugLessonLessonIdRoute
  '/lesson/$lessonId/edit': typeof LessonLessonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$courseSlug': typeof CourseSlugRouteWithChildren
  '/messages': typeof MessagesRoute
  '/test': typeof TestRoute
  '/$courseSlug/admin': typeof CourseSlugAdminRoute
  '/$courseSlug/dashboard': typeof CourseSlugDashboardRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/api/$': typeof ApiSplatRoute
  '/api/demo-events': typeof ApiDemoEventsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/$courseSlug/': typeof CourseSlugIndexRoute
  '/$courseSlug/lesson/$lessonId': typeof CourseSlugLessonLessonIdRoute
  '/lesson_/$lessonId/edit': typeof LessonLessonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$courseSlug'
    | '/messages'
    | '/test'
    | '/$courseSlug/admin'
    | '/$courseSlug/dashboard'
    | '/account/$accountView'
    | '/api/$'
    | '/api/demo-events'
    | '/api/messages'
    | '/auth/$authView'
    | '/$courseSlug/'
    | '/$courseSlug/lesson/$lessonId'
    | '/lesson/$lessonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/messages'
    | '/test'
    | '/$courseSlug/admin'
    | '/$courseSlug/dashboard'
    | '/account/$accountView'
    | '/api/$'
    | '/api/demo-events'
    | '/api/messages'
    | '/auth/$authView'
    | '/$courseSlug'
    | '/$courseSlug/lesson/$lessonId'
    | '/lesson/$lessonId/edit'
  id:
    | '__root__'
    | '/'
    | '/$courseSlug'
    | '/messages'
    | '/test'
    | '/$courseSlug/admin'
    | '/$courseSlug/dashboard'
    | '/account/$accountView'
    | '/api/$'
    | '/api/demo-events'
    | '/api/messages'
    | '/auth/$authView'
    | '/$courseSlug/'
    | '/$courseSlug/lesson/$lessonId'
    | '/lesson_/$lessonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseSlugRoute: typeof CourseSlugRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  TestRoute: typeof TestRoute
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiDemoEventsRoute: typeof ApiDemoEventsRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  LessonLessonIdEditRoute: typeof LessonLessonIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug': {
      id: '/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/$courseSlug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug/': {
      id: '/$courseSlug/'
      path: '/'
      fullPath: '/$courseSlug/'
      preLoaderRoute: typeof CourseSlugIndexRouteImport
      parentRoute: typeof CourseSlugRoute
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-events': {
      id: '/api/demo-events'
      path: '/api/demo-events'
      fullPath: '/api/demo-events'
      preLoaderRoute: typeof ApiDemoEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug/dashboard': {
      id: '/$courseSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$courseSlug/dashboard'
      preLoaderRoute: typeof CourseSlugDashboardRouteImport
      parentRoute: typeof CourseSlugRoute
    }
    '/$courseSlug/admin': {
      id: '/$courseSlug/admin'
      path: '/admin'
      fullPath: '/$courseSlug/admin'
      preLoaderRoute: typeof CourseSlugAdminRouteImport
      parentRoute: typeof CourseSlugRoute
    }
    '/lesson_/$lessonId/edit': {
      id: '/lesson_/$lessonId/edit'
      path: '/lesson/$lessonId/edit'
      fullPath: '/lesson/$lessonId/edit'
      preLoaderRoute: typeof LessonLessonIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$courseSlug/lesson/$lessonId': {
      id: '/$courseSlug/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/$courseSlug/lesson/$lessonId'
      preLoaderRoute: typeof CourseSlugLessonLessonIdRouteImport
      parentRoute: typeof CourseSlugRoute
    }
  }
}

interface CourseSlugRouteChildren {
  CourseSlugAdminRoute: typeof CourseSlugAdminRoute
  CourseSlugDashboardRoute: typeof CourseSlugDashboardRoute
  CourseSlugIndexRoute: typeof CourseSlugIndexRoute
  CourseSlugLessonLessonIdRoute: typeof CourseSlugLessonLessonIdRoute
}

const CourseSlugRouteChildren: CourseSlugRouteChildren = {
  CourseSlugAdminRoute: CourseSlugAdminRoute,
  CourseSlugDashboardRoute: CourseSlugDashboardRoute,
  CourseSlugIndexRoute: CourseSlugIndexRoute,
  CourseSlugLessonLessonIdRoute: CourseSlugLessonLessonIdRoute,
}

const CourseSlugRouteWithChildren = CourseSlugRoute._addFileChildren(
  CourseSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseSlugRoute: CourseSlugRouteWithChildren,
  MessagesRoute: MessagesRoute,
  TestRoute: TestRoute,
  AccountAccountViewRoute: AccountAccountViewRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiDemoEventsRoute: ApiDemoEventsRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  LessonLessonIdEditRoute: LessonLessonIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
