import type { Quiz } from './store'

const questions = [
  "I prefer to work in a structured, organized environment",
  "I enjoy experimenting with new techniques and materials",
  "I find inspiration in nature and organic forms",
  "I like to plan my projects in detail before starting",
  "I often work on multiple projects simultaneously",
  "I prefer working alone rather than in collaboration",
  "I'm drawn to bold, vibrant colors",
  "I value precision and technical excellence",
  "I enjoy breaking traditional rules and conventions",
  "I find meaning in abstract concepts and symbolism",
  "I prefer to complete one project before starting another",
  "I'm influenced by current trends and contemporary art",
  "I enjoy incorporating digital tools in my creative process",
  "I prefer working with traditional mediums",
  "I find inspiration in urban environments",
  "I enjoy the problem-solving aspects of creating",
  "I prefer spontaneous creation over planned execution",
  "I'm drawn to minimalist aesthetics",
  "I enjoy incorporating text or typography in my work",
  "I find inspiration in historical art movements",
  "I prefer working in a quiet, solitary environment",
  "I enjoy collaborative creative projects",
  "I'm influenced by music while creating",
  "I prefer symmetry and balance in my work",
  "I enjoy working with unconventional materials",
  "I find inspiration in personal experiences",
  "I prefer working on a large scale",
  "I enjoy detailed, intricate work",
  "I'm drawn to monochromatic color schemes",
  "I find inspiration in social issues",
  "I prefer working with a limited color palette",
  "I enjoy incorporating mixed media",
  "I'm influenced by cultural traditions",
  "I prefer working on commissioned projects",
  "I enjoy creating series or collections",
  "I find inspiration in dreams and imagination",
  "I prefer working in natural light",
  "I enjoy creating functional art",
  "I'm drawn to geometric patterns",
  "I find inspiration in literature",
  "I prefer working with a specific medium",
  "I enjoy experimental techniques",
  "I'm influenced by emotional states",
  "I prefer working on small-scale projects",
  "I enjoy creating narrative works",
  "I find inspiration in architectural forms",
  "I prefer working with organic shapes",
  "I enjoy creating interactive art",
  "I'm drawn to texture and tactile elements",
  "I find inspiration in scientific concepts"
]

export const defaultQuiz: Quiz = {
  title: "Artist Type Assessment",
  version: "1.0.0",
  questions: questions.map((content, index) => ({
    id: `q${index + 1}`,
    type: "rating",
    title: `Question ${index + 1}`,
    content,
    points: 1,
    timeLimit: 30,
    minLabel: "Strongly Disagree",
    maxLabel: "Strongly Agree",
    min: 1,
    max: 10
  }))
} 